services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - src/.env
    volumes:
      - ./logs:/app/logs
      - ./src/core:/app/core
    networks:
      - discord-bot-network
